/* The content API.
 *
 * Everything here reads `src/content/bundle.json`, which is generated by
 * `npm run content` (tools/build.py --bundle). No markdown is parsed in this
 * app: the Python pipeline owns the directive syntax, the clause numbering,
 * the search index and the structured data, and this app renders what it is
 * given. That is the whole reason the two builds cannot drift.
 */

import bundleJson from "@/content/bundle.json";

export type Block =
    | { type: "prose"; html: string }
    | { type: "lede"; html: string }
    | { type: "note"; html: string }
    | { type: "heading"; level: number; id: string; clause: string; alias: string; text: string }
    | { type: "terms"; items: { term: string; html: string }[] }
    | { type: "def"; term: string; ref: string; html: string }
    | { type: "diagram"; name: string; n: number; caption: string }
    | { type: "matrix"; n: number; mark: number[]; caption: string; note: string }
    | { type: "faq"; items: { q: string; id: string; html: string }[] }
    | { type: "split"; ratio: string; columns: Block[][] };

export interface Part {
    n: number;
    slug: string;
    name: string;
    count: number;
    blurb: string;
}

export interface Entry {
    clause: string;
    part: number;
    slug: string;
    title: string;
    short_title: string;
    description: string;
    keywords: string[];
    defines: string;
    reading_minutes: number;
    cited_by: number;
    canonical_entry: boolean;
    quick_facts: Record<string, string>;
    related: string[];
    sources: string[];
    prev: { ref: string; title: string } | null;
    next: { ref: string; title: string } | null;
    sections: { id: string; clause: string; text: string }[];
    figure_count: number;
    url: string;
    part_slug: string;
    blocks: Block[];
    ld: Record<string, unknown>[];
}

export interface IndexTerm {
    t: string;
    ref: string;
    key: boolean;
    example: boolean;
    template: boolean;
    level: string;
    url: string;
    flags: string;
}

interface Bundle {
    site: {
        site: {
            name: string;
            short_name: string;
            origin: string;
            base_path: string;
            locale: string;
            description: string;
            entries_total: number;
            parts_total: number;
        };
        editorial: {
            standfirst: string;
        };
        home: {
            title: string;
            blurb: string;
            chips: string[];
            start_here: string[];
            most_cited: { title: string; ref: string; count: number }[];
            maintenance: { label: string; body: string };
        };
    };
    ld: Record<string, unknown>[];
    index_ld: Record<string, unknown>[];
    parts: Part[];
    entries: Entry[];
    index: { terms: IndexTerm[]; coverage: string[] };
    pages: { not_found: string };
}

const bundle = bundleJson as unknown as Bundle;

export const config = bundle.site;
export const site = bundle.site.site;
export const editorial = bundle.site.editorial;
export const home = bundle.site.home;
export const parts = bundle.parts;
export const entries = bundle.entries;
export const pages = bundle.pages;
export const siteLd = bundle.ld;
export const indexLd = bundle.index_ld;
export const indexTerms = bundle.index.terms;
export const coverage = bundle.index.coverage;

/** Site-root path -> the path a browser should request. */
export function href(path: string): string {
    const base = site.base_path || "/";
    return base.replace(/\/$/, "") + "/" + path.replace(/^\//, "");
}

export function absolute(path: string): string {
    return site.origin.replace(/\/$/, "") + href(path);
}

export function byClause(clause: string): Entry | undefined {
    return entries.find((e) => e.clause === clause);
}

export function partBySlug(slug: string): Part | undefined {
    return parts.find((p) => p.slug === slug);
}

export function entriesInPart(n: number): Entry[] {
    return entries.filter((e) => e.part === n);
}

export function navTitle(entry: Entry): string {
    return entry.short_title || entry.title;
}

/** Parts with at least one published entry. Empty parts get no page. */
export function livePartsOnly(): Part[] {
    return parts.filter((p) => entriesInPart(p.n).length > 0);
}

export function graph(nodes: Record<string, unknown>[]) {
    return { "@context": "https://schema.org", "@graph": nodes };
}
